<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArtworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtworkRepository extends EntityRepository
{
    /**
     * @return Artwork
     */
    public function findWithParticipants($id)
    {
        return $this->createQueryBuilder('a')
            ->addSelect('p')
            ->leftJoin('a.participants', 'p')
            ->where('a.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getSingleResult();
    }
}
